spring:
#redis服务器相关配置
  redis:
      sentinel:
        master: mymaster
        nodes:
      host: 127.0.0.1
      password:
      port: 6379
      pool:
        min-idle: 20
        max-idle: 20
        max-active: 100
        max-wait: -1
      timeout: 1000
      #通过@Cacheable代理的缓存默认失效时间(单位：秒)
      cacheableDefaultExpSec: 120
      #设置自定义的缓存失效时间 example1:72，example2:720，...
      expires: weixinjsapi:7200
      database: 1
  # Server settings
  #  项目启动地址：http://localhost:8080/wechat/toLogin
  server:
      port:8080
      address:127.0.0.1

  # DATASOURCE
  jdbc:
      dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      url: 'jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&useSSL=true'
      databaseName: 'wechat'
      serverName: '127.0.0.1'
      username: 'root'
      password: 'root'
      cachePrepStmts: true
      prepStmtsSize: 250
      prepStmtsCacheSqlLimit: 2048
      userServerPrepStmts: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  thymeleaf:
      cache: false
      cache-period: 0
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
  template:
      cache: false
  # SPRING PROFILES
  spring:
      # HTTP ENCODING
      http:
          encoding.charset: UTF-8
          encoding.enable: true
          encoding.force: true

  # MyBatis
  mybatis:
      typeAliasesPackage: com.wechat.model
      mapperLocations: classpath:mapper/*.xml
      #configLocation: classpath:/mybatis-config.xml
      configuration:
              callSettersOnNulls: true
              map-underscore-to-camel-case: true
              default-fetch-size: 100
              default-statement-timeout: 30

  # LOGGING
  logging:
      config : classpath:logback-boot.xml
      level:
         com.ibatis:DEBUG
mq:
  namesrvAddr: 192.168.211.223:9876
  producerGroup: CommonsProducer
  timeout: 3000
  retryTimes: 5
