spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/
#redis服务器相关配置
  redis:
      sentinel:
        master: mymaster
        nodes:
      host: 47.98.101.128
      password:
      port: 6379
      pool:
        min-idle: 20
        max-idle: 20
        max-active: 100
        max-wait: -1
      timeout: 1000
      #通过@Cacheable代理的缓存默认失效时间(单位：秒)
      cacheableDefaultExpSec: 120
      #设置自定义的缓存失效时间 example1:72，example2:720，...
      expires: weixinjsapi:7200
      database: 1
  thymeleaf:
  # tiles 定义文件所在的位置，多个用逗号隔开如"classpath:/templates/tiles-defs-member.xml,classpath:/templates/tiles-defs-order.xml"
#      tilesDefLocations: "classpath:/templates/tiles-defs.xml"
#      excludedViewNames: [member/*,demo/*,merchant/*,jk51b/*,store/*,wechat/*, product/*,login/*,account/*]
      cache: false
      cache-period: 0
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
  # DATASOURCE
  jdbc:
      dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      url: 'jdbc:mysql://47.98.101.128:3306/wechat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&useSSL=true'
      databaseName: 'wechat'
      serverName: 'aliyun'
      username: 'root'
      password: '123456'
      driverClassName: 'com.mysql.jdbc.Driver'
      type: com.alibaba.druid.pool.DruidDataSource
#      cachePrepStmts: false
      prepStmtsSize: 250
      prepStmtsCacheSqlLimit: 2048
      userServerPrepStmts: true
      filters: stat,slf4j,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  http:
    encoding:
      force: true
    #文件上传,文件最大值设置
    multipart:
      maxFileSize: 15Mb       #单个文件最大值
      maxRequestSize: 150Mb   #单次请求文件总数最大值
  # Server settings
  #  项目启动地址：http://localhost:8080/wechat/toLogin
server:
  port: 8081
  address: 127.0.0.1
  contextPath: /
      # Tomcat特性相关
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    connectionTimeout: 180000
    basedir:
    # secs
    backgroundProcessorDelay: 30
  template:
      cache: false
# MyBatis
mybatis:
  configLocation: classpath:/mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.wechat.model
  configuration:
      callSettersOnNulls: true
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30

#配置日志
logging:
      config : classpath:logback-boot.xml
mq:
  namesrvAddr: 47.98.101.128:9876
  producerGroup: CommonsProducer
  timeout: 3000
  retryTimes: 5

#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql;pageNum=pagenum;pageSize=pagesize

#下载的临时文件夹
report:
  temp_dir: D:/reports
